### ISSUE TITLE
API key not saving

### ISSUE THREAD

**Issue by FootPrintStudio** [jordanhandy/obsidian-imgbb-uploader#1]
The API key is not saving, I've tried multiple times, but each time I attempt to paste or drag and drop an image, I get the error that I haven't set the API key. I've tried on a fresh vault with the same issue, so unlikely that it's affected by another plugin.

**Comment by jordanhandy** [comment]
Hi @FootPrintStudio 

I can't seem to reproduce this.  When you paste the API key in the appropriate field, you should be receiving a Notice from the app that the API key was saved and encrypted.  At this point, you should be able to exit the settings pane and attempt an upload. I've attached an example quick video below (see link).

Do you see any other messages via Notice, or if you toggle the developer console, do you see any error messages?

macOS → `cmd+option+i`
Windows → `ctrl+shift+i`

https://ibb.co/hMWYBgr

**Comment by FootPrintStudio** [comment]
This is all I get in the console regarding the plugin.
![image](https://github.com/user-attachments/assets/9f28d959-61e2-403d-bfce-34fda8c45f3e)

I paste the key as instructed; however, when attempting to paste anything I get this error.
![image](https://github.com/user-attachments/assets/f02c35d1-fcec-4de4-ac1d-b64f9920133f)

**Comment by FootPrintStudio** [comment]
Ok I realized what was happening; however, there's still a major usability issue. When testing I wasn't pasting an image, I was pasting an image URL such as (https://www.aviationgin.com/images/aag_botanicals.jpg), 90% of the time this is how I usually add images to my vault, so it would be great if the plugin could handle that. 

But, perhaps more importantly, it that the plugin seems to block the ability to paste anything if the "Paste via clipboard copy/paste?" setting is on unless it is an image. Having a the plugin parse what is an image (or image link) and not, would make this plugin very useful, unfortunately, it is otherwise a little unwieldy. Using the drag/drop feature is still valuable, but I'd love to see those UX concerns addressed.

**Comment by jordanhandy** [comment]
Out of curiosity, what would be the use case for pasting an image URL instead of the image itself? The URL you provided is the image source, so what constitutes a difference in workflow where you would otherwise intuitively want to paste an image into a multimedia application (instead of the image URL)?

**Comment by FootPrintStudio** [comment]
Haha, you know when you put it like that, I don't have a good answer, I guess I'm just a little stuck in my workflow... Fair enough, any thoughts on the second thing?

**Comment by jordanhandy** [comment]
The second issue you pointed out seems like a bug. I've got some time to work on this now. I'll post an update when complete.

**Comment by jordanhandy** [comment]
@FootPrintStudio 

Latest update should fix the global paste issue for items that are not images.
There is also now the option to parse image source links :) 

This was put together a tad hastily, so let me know if you have any other issues

![image](https://github.com/user-attachments/assets/eec329ee-9825-4b2c-aab8-320bfc821ac0)

**Comment by FootPrintStudio** [comment]
Nice job! Just checked the update and it all seems to work.

**Comment by jordanhandy** [comment]
Awesome.  I'll close this for now
